version: '3'
services:
  mysql-intervook-auth:
    image: mysql:8.0
    container_name: mysql-intervook-auth
    ports:
      - "3806:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intervook
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - intervook-auth-mysql-volume:/var/lib/mysql
  mysql-intervook-contents:
    image: mysql:8.0
    container_name: mysql-intervook-contents
    ports:
      - "3906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intervook
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - intervook-contents-mysql-volume:/var/lib/mysql


volumes:
  intervook-auth-mysql-volume:
    driver: local
  intervook-contents-mysql-volume:
    driver: local
