spring:
  config:
    activate:
      on-profile: mysql_dev
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3806/interview-helper
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: mysql_aws_dev
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3806/interview-helper
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: mysql_prod
  jpa:
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3806/interview-helper
    username: root
    password: root

