spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3806/interview-helper
    username: root
    password: root

logging:
  level:
    root: info

frontend-url: ${FRONTEND_URL:http://localhost:33000}
file:
  service-url: http://localhost:${server.port}/image
