spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3806/interview-helper
    username: root
    password: root

logging:
  level:
    root: debug

frontend-url: ${FRONTEND_URL:http://localhost:33000}
