spring:
  config:
    activate:
      on-profile: mysql_dev
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    auth:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3806/intervook
      username: root
      password: root
    contents:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3906/intervook
      username: root
      password: root

---
spring:
  config:
    activate:
      on-profile: mysql_aws_dev
  flyway:
    enabled: false
  jpa:
    show-sql: true
  datasource:
    auth:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3806/intervook
      username: root
      password: root
    contents:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3906/intervook
      username: root
      password: root

---
spring:
  config:
    activate:
      on-profile: mysql_prod
  flyway:
    enabled: false
  jpa:
    show-sql: false
  datasource:
    auth:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3806/intervook
      username: root
      password: root
    contents:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3906/intervook
      username: root
      password: root

