version: '3'
services:
  mysql-interview-helper:
    image: mysql:8.0
    container_name: mysql-interview-helper
    ports:
      - "3806:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interview-helper
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - interview-helper-mysql-volume:/var/lib/mysql

volumes:
  interview-helper-mysql-volume:
    driver: local
